import { TeamMember } from "@/types/type";

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: "ayushi-satodiya",
    name: "Ayushi Satodiya",
    role: "Team Lead",
    department: "BSC IT",
    img: "/images/team-member/ayushi-satodiya.png",
    socialLinks: {
      linkedin: "https://www.linkedin.com/in/ayushi-satodiya-836a47329/",
      github: "https://github.com/johndoe",
      twitter: "https://twitter.com/johndoe",
    },
    expertise: ["Machnine Learning", "Data Analysis", "Algorithms"],
    bio: "Experienced technical leader with 10+ years in software development",
    bgGradientColor: "#4E2C6C",
  },
  {
    id: "anand-trambadiya",
    name: "Anand Trambadiya",
    role: "Team Lead",
    department: "Leadership and Development",
    img: "/images/team-member/anand-tambadiya.jpeg",
    socialLinks: {
      linkedin: "https://www.linkedin.com/in/anandtrambadiya",
      github: "https://github.com/anandtrambadiya",
    },
    expertise: ["Data Science and Applications", "IoT and Automation", "Full-Stack Web Development"],
    bio: "Data science enthusiast with expertise in IoT, automation, and web technologies. Passionate about combining leadership and technology to drive impactful solutions.",
    bgGradientColor: "#2A558C",
  },
  {
    id: "krishna-dharsandia",
    name: "Krishna Dharsandia",
    role: "App Development Lead",
    department: "Mobile Development",
    img: "/images/team-member/krishna-dharsandia.png",
    socialLinks: {
      linkedin: "https://www.linkedin.com/in/krishna-dharsandia-351904250/",
      github: "https://github.com/KRISHNA-DHARSANDIA",
    },
    expertise: ["Mobile App Development", "Cross-Platform Solutions", "Performance Optimization"],
    bio: "Mobile technology expert specializing in React Native and Flutter",
    bgGradientColor: "#2C6A2F",
  },
  {
    id: "Jenil-Desai",
    name: "Jenil Desai",
    role: "Web Development Lead",
    department: "CS & IT",
    img: "/images/team-member/jenil-desai.jpeg",
    socialLinks: {
      linkedin: "https://www.linkedin.com/in/desaijenil",
      github: "https://github.com/Jenil-Desai",
    },
    expertise: ["Docker & Kubernetes", "Linux Administration", "Full Stack Web Development", "React Native (Beginner)"],
    bio: "Web development expert skilled in building full-stack solutions, managing containerized environments, and working with Linux systems. Passionate about learning new technologies, currently exploring React Native for mobile development.",
    bgGradientColor: "#2C6A2F",
  },
  {
    id: "dev-kacha",
    name: "Dev Kacha",
    role: "Web Development Lead",
    department: "Computer Application",
    img: "/images/team-member/dev-kacha.jpeg",
    socialLinks: {
      linkedin: "https://www.linkedin.com/in/dev-kacha",
      github: "https://github.com/devkacha03",
    },
    expertise: ["Fornt-End Web Development", "Database (Oracle)"],
    bio: "Innovative Front-End Developer specializing in building scalable and user-friendly web applications. Passionate about leveraging modern technologies like ReactJs to create impactful digital experiences.",
    bgGradientColor: "#2C6A2F",
  },
  {
    id: "punit-gondaliya",
    name: "Punit Gondaliya",
    role: "UI/UX Lead",
    department: "CS & IT",
    img: "/images/team-member/punit-gondaliya.jpeg",
    socialLinks: {
      linkedin: "https://in.linkedin.com/in/punitgondaliya/",
      github: "https://github.com/PunitGondaliya2/",
    },
    expertise: ["UI/UX Design", "Web Design", "Content Producing"],
    bio: "UI/UX enthusiast with 3 years of experience in Design and Content Creation, expanding my skills in Web Development.",
    bgGradientColor: "#5302FF",
  },
  {
    id: "kishan-viradiya",
    name: "Kishan Viradiya",
    role: "AI / ML Lead",
    department: "Artificial Intelligence",
    img: "/images/team-member/kishan-viradiya.jpeg",
    socialLinks: {
      linkedin: "www.linkedin.com/in/kishanviradiya",
      github: "https://github.com/Kishan1405",
    },
    expertise: ["AI Industrial Application", "Model Training", "Leadership"],
    bio: "I am an AI Prompt Engineer and ML Enthusiast, specializing in industry AI integration and innovation.",
    bgGradientColor: "#2C6A2F",
  },
  {
    id: "Cheshta Trivedi",
    name: "Cheshta Trivedi",
    role: "Marketing Lead",
    department: "CS & IT",
    img: "/images/team-member/cheshta-trivedi.jpeg",
    socialLinks: {
      linkedin: "https://www.linkedin.com/in/cheshta-trivedi-840670260",
      github: "https://github.com/cheshta-10",
    },
    expertise: ["Front-end Developer", "Social-media Management", "Content writing"],
    bio: "I'm passionate about helping organizations make smarter decisions by strong foundation of Power-BI . Also worked as a content writer & Social- Media Management",
    bgGradientColor: "#5302FF",
  },
];
